
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cup;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CHAR = 7;
  public static final int LIT_FLOAT = 10;
  public static final int DELIMITADOR = 51;
  public static final int BLOQUE_C = 45;
  public static final int CASE = 36;
  public static final int DIFERENTE = 27;
  public static final int RESTA = 15;
  public static final int INTEGER = 4;
  public static final int BLOQUE_A = 44;
  public static final int DOS_PUNTOS = 40;
  public static final int CORCHETE_C = 47;
  public static final int CORCHETE_A = 46;
  public static final int NEGATIVO = 43;
  public static final int FOR = 34;
  public static final int IDENTIFICADOR = 3;
  public static final int IGUALDAD = 26;
  public static final int BOOL = 6;
  public static final int INCREMENTO = 20;
  public static final int SUMA = 14;
  public static final int MAIN = 2;
  public static final int IF = 31;
  public static final int PUNTO_COMA = 42;
  public static final int EOF = 0;
  public static final int RETURN = 39;
  public static final int DECREMENTO = 21;
  public static final int error = 1;
  public static final int COMA = 41;
  public static final int LIT_STRING = 12;
  public static final int MODULO = 18;
  public static final int NEGACION = 30;
  public static final int MENOR = 22;
  public static final int LIT_CHAR = 11;
  public static final int BREAK = 38;
  public static final int ASIGNACION = 50;
  public static final int SWITCH = 35;
  public static final int MAYOR = 24;
  public static final int POTENCIA = 19;
  public static final int ELSE = 32;
  public static final int READ = 53;
  public static final int LIT_INTEGER = 9;
  public static final int PARENTESIS_C = 49;
  public static final int WHILE = 33;
  public static final int PARENTESIS_A = 48;
  public static final int DEFAULT = 37;
  public static final int MAYOR_IGUAL = 25;
  public static final int FLOAT = 5;
  public static final int CONJUNCION = 28;
  public static final int LIT_BOOL = 13;
  public static final int STRING = 8;
  public static final int DISYUNCION = 29;
  public static final int MENOR_IGUAL = 23;
  public static final int DIVISION = 16;
  public static final int PRINT = 52;
  public static final int MULTIPLICACION = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "IDENTIFICADOR",
  "INTEGER",
  "FLOAT",
  "BOOL",
  "CHAR",
  "STRING",
  "LIT_INTEGER",
  "LIT_FLOAT",
  "LIT_CHAR",
  "LIT_STRING",
  "LIT_BOOL",
  "SUMA",
  "RESTA",
  "DIVISION",
  "MULTIPLICACION",
  "MODULO",
  "POTENCIA",
  "INCREMENTO",
  "DECREMENTO",
  "MENOR",
  "MENOR_IGUAL",
  "MAYOR",
  "MAYOR_IGUAL",
  "IGUALDAD",
  "DIFERENTE",
  "CONJUNCION",
  "DISYUNCION",
  "NEGACION",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "RETURN",
  "DOS_PUNTOS",
  "COMA",
  "PUNTO_COMA",
  "NEGATIVO",
  "BLOQUE_A",
  "BLOQUE_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "ASIGNACION",
  "DELIMITADOR",
  "PRINT",
  "READ"
  };
}

